version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    environment:
      - MH_UI_WEB_PATH=/
      - MH_UI_BIND_ADDR=0.0.0.0:8025
      - MH_API_BIND_ADDR=0.0.0.0:80
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8025"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Add other test services here as needed

networks:
  default:
    name: agentflow-test-network
