  /auth/login:
    get:
      summary: Login
      description: Redirect to authentication provider for login
      operationId: login
      responses:
        '302':
          description: Redirect to authentication provider
  
  /auth/callback:
    get:
      summary: Authentication callback
      description: Callback endpoint for authentication provider
      operationId: authCallback
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
        - name: state
          in: query
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirect to application after successful authentication
        '401':
          description: Authentication failed
  
  /auth/logout:
    get:
      summary: Logout
      description: Logout the current user
      operationId: logout
      security:
        - cookieAuth: []
      responses:
        '302':
          description: Redirect to login page after logout
  
  /auth/user:
    get:
      summary: Get current user
      description: Get information about the currently authenticated user
      operationId: getCurrentUser
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Current user information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized - User ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
