  /credentials:
    get:
      summary: List all credentials
      description: Get a list of all credentials for the authenticated user
      operationId: listCredentials
      security:
        - cookieAuth: []
      parameters:
        - name: platform
          in: query
          required: false
          schema:
            type: string
          description: Filter credentials by platform
      responses:
        '200':
          description: List of credentials
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    platform:
                      type: string
                    label:
                      type: string
                    created:
                      type: string
                      format: date-time
                    updated:
                      type: string
                      format: date-time
                    hasRefreshToken:
                      type: boolean
                    data:
                      type: object
                      description: Platform-specific credential data
        '401':
          description: Unauthorized - User ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    post:
      summary: Add a new credential
      description: Create a new credential for the authenticated user
      operationId: addCredential
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                platform:
                  type: string
                  description: Platform identifier
                label:
                  type: string
                  description: User-friendly label for the credential
                data:
                  type: object
                  description: Platform-specific credential data
                refreshToken:
                  type: string
                  description: Optional refresh token
                refreshTokenExpiry:
                  type: string
                  format: date-time
                  description: Optional refresh token expiry date
              required:
                - platform
                - data
      responses:
        '201':
          description: Credential created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  platform:
                    type: string
                  label:
                    type: string
                  created:
                    type: string
                    format: date-time
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - User ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /credentials/{id}:
    get:
      summary: Get credential by ID
      description: Get details of a specific credential
      operationId: getCredential
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Credential details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  platform:
                    type: string
                  label:
                    type: string
                  created:
                    type: string
                    format: date-time
                  updated:
                    type: string
                    format: date-time
                  hasRefreshToken:
                    type: boolean
                  data:
                    type: object
                    description: Platform-specific credential data
        '401':
          description: Unauthorized - User ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Credential not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    put:
      summary: Update credential
      description: Update an existing credential
      operationId: updateCredential
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                label:
                  type: string
                  description: User-friendly label for the credential
                data:
                  type: object
                  description: Platform-specific credential data
                refreshToken:
                  type: string
                  description: Optional refresh token
                refreshTokenExpiry:
                  type: string
                  format: date-time
                  description: Optional refresh token expiry date
                active:
                  type: boolean
                  description: Whether the credential is active
      responses:
        '200':
          description: Credential updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  platform:
                    type: string
                  label:
                    type: string
                  updated:
                    type: string
                    format: date-time
        '401':
          description: Unauthorized - User ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Credential not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    delete:
      summary: Delete credential
      description: Delete a credential (soft delete)
      operationId: deleteCredential
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Credential deleted successfully
        '401':
          description: Unauthorized - User ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Credential not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
